
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
  - name: workspace-git
    type: git
  - name: bwce-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: bwce-build
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: workspace-git
      outputs:
      - name: image
        resource: bwce-image
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build
    params:
    - name: ARGS
      value: "new-app samplehttp"