apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: bwce-build
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
  outputs:
    resources:
      - name: image
        type: image
  steps:
  - name: build
    image: quay.io/buildah/stable
    command: 
      - "buildah"
    args:
      - 'bud'
      - '--layers'
      - '-t'
      - '$(outputs.resources.image.url)'
      - '.'
    workingDir: /workspace/tibco.bwce.sample.palette.http.RequestResponse.application/target
    securityContext:
      privileged: true
      runAsUser: 0
  - name: list
    image: quay.io/buildah/stable
    command: 
      - "buildah"
    args:
      - 'images'
  - name: push
    image: quay.io/buildah/stable
    command: 
      - "buildah"
    args:
      - 'push'
      - '$(outputs.resources.image.url)'
      - 'docker://$(outputs.resources.image.url)'



 # - name: build
 #   image: maven:3.6.0-jdk-8-slim
 #   command: ['/usr/bin/mvn','clean','package','initialize','docker:build','docker:push']
 #   workingDir: /workspace/tibco.bwce.sample.palette.http.RequestResponse.application.parent
    #args:
    #- clean package initialize docker:build docker:push